---
- hosts: kubes_nodes
  remote_user: pirate
  become: yes
  become_user: root
  handlers:
    - name: restart chrony
      service: name=chrony state=restarted
      listen: "restart chrony service"

  tasks:
    - name: Configure kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        update_cache: yes
    - name: Add GPG key for kubernetes
      apt_key:
        url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
        state: present
    - name: Install kubeadm
      apt:
        name: kubeadm
        state: latest
        update_cache: yes
        cache_valid_time: 3600
 
    - name: update cache and install chrony
      apt:
        name: chrony
        state: latest
        update_cache: yes
        cache_valid_time: 3600
    - name: template chrony.conf
      template: src=templates/chrony.j2 dest=/etc/chrony/chrony.conf
      notify: "restart chrony service"
    - name: ensure chrony service is running
      service:
        name: chrony
        state: started 
    - name: set timezone to America/New_York
      timezone:
        name: America/New_York
  
